# Generated by Django 5.0.6 on 2024-06-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
