# Generated by Django 5.0.6 on 2024-06-24 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_client', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='RestaurantClient',
        ),
    ]
