# Generated by Django 5.0.6 on 2024-06-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_client', '0002_rename_client_restaurantclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantclient',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantclient',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
