# Generated by Django 5.0.6 on 2024-06-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_reservation_hash_reservation_reservation_hash_and_more'),
        ('restaurant_client', '0003_restaurantclient_birthdate_restaurantclient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantclient',
            name='reservations',
            field=models.ManyToManyField(related_name='restaurant_clients', to='reservation.reservation'),
        ),
    ]
