# Generated by Django 5.0.9 on 2025-01-04 03:53

from django.db import migrations
from django.db import models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_main_unit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=models.CASCADE, related_name='units', to='restaurant.Restaurant', db_index=True)),
            ],
            options={
                'db_table': 'restaurant_unit',
                'unique_together': {('restaurant', 'name')},
            },
        ),
    ]
