# Generated by Django 5.0.6 on 2024-07-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantCustomer',
            fields=[
                ('name', models.CharField(db_index=True, max_length=100)),
                ('lastname', models.CharField(db_index=True, max_length=100)),
                ('country_code', models.CharField(max_length=3)),
                ('phone', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('reservations', models.ManyToManyField(related_name='restaurant_customers', to='reservation.reservation')),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'lastname', 'phone'], name='restaurant__name_78fb79_idx')],
            },
        ),
    ]
