# Generated by Django 5.0.9 on 2025-01-03 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_customer', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantcustomer',
            name='preferred_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regular_customers', to='unit.unit'),
        ),
    ]
