# Generated by Django 5.0.9 on 2024-11-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_reservation_user_and_more'),
        ('restaurant_customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantcustomer',
            name='reservations',
            field=models.ManyToManyField(related_name='customers', to='reservation.reservation'),
        ),
    ]
