# Generated by Django 5.0.9 on 2024-12-31 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_customer', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantcustomer',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='restaurantcustomer',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='restaurantcustomer',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='unit_customers', to='unit.unit'),
        ),
    ]
