# Generated by Django 5.0.9 on 2024-12-09 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantcustomer',
            name='reservations',
        ),
    ]
