# Generated by Django 5.0.9 on 2025-01-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_initial'),
        ('restaurant_customer', '0002_restaurantcustomer_restaurants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantcustomer',
            name='restaurants',
            field=models.ManyToManyField(related_name='customer_restaurants', to='restaurant.restaurant'),
        ),
    ]
