# Generated by Django 5.0.9 on 2024-12-24 22:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_customer', '0003_alter_restaurantcustomer_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantcustomer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
