# Generated by Django 5.0.8 on 2024-10-22 22:38

import custom_auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
        ('custom_auth', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='restaurant.restaurantemployee'),
        ),
        migrations.AddField(
            model_name='account',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_accounts', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customeruser_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customeruser_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='account',
            field=models.ForeignKey(default=custom_auth.models.get_default_account, on_delete=django.db.models.deletion.CASCADE, to='custom_auth.account'),
        ),
        migrations.AddField(
            model_name='session',
            name='account',
            field=models.ForeignKey(default=custom_auth.models.get_default_account, on_delete=django.db.models.deletion.CASCADE, to='custom_auth.account'),
        ),
        migrations.AddIndex(
            model_name='verificationtoken',
            index=models.Index(fields=['token'], name='token_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['provider', 'provider_account_id'], name='provider_account_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['access_token'], name='access_token_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['expires_at'], name='expires_at_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['session_token'], name='session_token_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['expires'], name='expires_idx'),
        ),
    ]
