# Generated by Django 5.0.9 on 2025-01-03 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('custom_auth', '0001_initial'),
        ('restaurant', '0002_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_users', to='unit.unit'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customeruser_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='custom_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='verificationtoken',
            index=models.Index(fields=['token'], name='token_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['custom_user_id', 'email'], name='custom_user__id_email_idx'),
        ),
    ]
