# Generated by Django 5.0.8 on 2024-10-24 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_account_is_system_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_system_account',
        ),
    ]
