# Generated by Django 5.0.8 on 2024-10-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_remove_account_is_system_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_system_account',
            field=models.BooleanField(default=False),
        ),
    ]
