# Generated by Django 5.0.9 on 2024-12-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('custom_auth', '0005_alter_customuser_restaurant'),
        ('restaurant', '0005_alter_restaurantemployee_table'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['custom_user_id', 'email'], name='custom_user__id_email_idx'),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='custom_user',
        ),
        migrations.AlterModelTable(
            name='loginlog',
            table='login_log',
        ),
        migrations.AlterModelTable(
            name='verificationtoken',
            table='verification_token',
        ),
    ]
