# Generated by Django 5.0.9 on 2024-11-02 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_blacklistedtoken'),
        ('restaurant', '0002_alter_restaurantemployee_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_accounts', to='restaurant.restaurantemployee'),
        ),
        migrations.AlterField(
            model_name='account',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_accounts', to='restaurant.restaurant'),
        ),
    ]
