# Generated by Django 5.0.9 on 2024-11-08 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0008_account_add_restaurant_employee'),
        ('restaurant', '0003_remove_restaurant_sessions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
