# Generated by Django 5.0.9 on 2024-11-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0010_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('RESTAURANTCUSTOMER', 'RestaurantCustomer'), ('ADMIN', 'Admin'), ('RESTAURANT_ADMIN', 'Restaurant Admin'), ('RESTAURANT_STAFF', 'Restaurant Staff')], default='RESTAURANT_STAFF', max_length=50),
        ),
    ]
