# Generated by Django 5.0.6 on 2024-07-19 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=9)),
                ('street', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=10)),
                ('neighborhood', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=30)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='restaurant.restaurant')),
            ],
            options={
                'indexes': [models.Index(fields=['address_id'], name='address_add_address_b40e1b_idx')],
                'unique_together': {('cep', 'street', 'number', 'neighborhood', 'city', 'state', 'country')},
            },
        ),
    ]
