# Generated by Django 5.0.8 on 2024-10-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=9)),
                ('street', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=10)),
                ('neighborhood', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=30)),
                ('complement', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
