# Generated by Django 5.0.9 on 2025-01-04 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='unit',
            field=models.OneToOneField(db_column='unit_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='unit.unit'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['address_id'], name='address_address_e701d2_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['cep'], name='address_cep_a6f9b0_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city', 'state'], name='address_city_daed79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('cep', 'street', 'number', 'neighborhood', 'city', 'state', 'country')},
        ),
    ]
