# Generated by Django 5.0.8 on 2024-10-22 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_addresses', to='restaurant.restaurant'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['address_id'], name='address_add_address_b40e1b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('cep', 'street', 'number', 'neighborhood', 'city', 'state', 'country')},
        ),
    ]
