# Generated by Django 5.0.6 on 2024-06-24 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('cep', 'street', 'street', 'number', 'neighborhood', 'city', 'state', 'country')},
        ),
    ]
