# Generated by Django 5.0.9 on 2024-11-24 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_address_address_id_alter_address_restaurant'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='address',
            new_name='address_address_e701d2_idx',
            old_name='address_add_address_b40e1b_idx',
        ),
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
    ]
