# Generated by Django 5.0.6 on 2024-06-26 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_rename_id_address_address_id'),
        ('restaurant', '0002_remove_restaurant_cep_remove_restaurant_city_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('cep', 'street', 'number', 'neighborhood', 'city', 'state', 'country')},
        ),
        migrations.AddField(
            model_name='address',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='restaurant.restaurant'),
        ),
    ]
