# Generated by Django 5.0.9 on 2025-01-04 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_alter_address_id_type'),
    ]

    operations = [
    ]
