# Generated by Django 5.0.9 on 2024-12-26 05:10

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_address_created_at_address_updated_at'),
        ('restaurant', '0007_restaurantemployee_country_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='address',
            name='address_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='cep',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='CEP must be in the format 00000-000', regex='^\\d{5}-?\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['cep'], name='address_cep_a6f9b0_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city', 'state'], name='address_city_daed79_idx'),
        ),
    ]
