# Generated by Django 5.0.6 on 2024-06-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('cnpj', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=9)),
                ('street', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('neighborhood', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='restaurant/images')),
            ],
        ),
    ]
