# Generated by Django 5.0.9 on 2025-01-03 02:16

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineType',
            fields=[
                ('cuisine_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cuisine_type',
            },
        ),
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Restaurant Categories',
                'db_table': 'restaurant_category',
            },
        ),
        migrations.CreateModel(
            name='RestaurantEmployee',
            fields=[
                ('employee_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('country_code', models.CharField(blank=True, max_length=3, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('RESTAURANT_ADMIN', 'Restaurant Administrator'), ('UNIT_ADMIN', 'Unit Administrator'), ('UNIT_SUB_ADMIN', 'Unit Sub Administrator'), ('UNIT_STAFF', 'Unit Staff')], default='UNIT_STAFF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'restaurant_employee',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(db_index=True, max_length=14, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('country_code', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('email_verified', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('RESTAURANT_ADMIN', 'Restaurant Administrator'), ('UNIT_ADMIN', 'Unit Administrator'), ('UNIT_SUB_ADMIN', 'Unit Sub Administrator'), ('UNIT_STAFF', 'Unit Staff')], default='RESTAURANT_ADMIN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL)),
                ('cuisine_types', models.ManyToManyField(related_name='restaurants', to='restaurant.cuisinetype')),
            ],
            options={
                'db_table': 'restaurant',
            },
        ),
    ]
