# Generated by Django 5.0.9 on 2025-01-04 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantemployee',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_employees', to='unit.unit'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['restaurant_id', 'name'], name='restaurant__id_name_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantemployee',
            index=models.Index(fields=['first_name', 'last_name', 'email'], name='restaurant_employee_idx'),
        ),
    ]
