# Generated by Django 5.0.8 on 2024-10-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='restaurantemployee',
            index=models.Index(fields=['restaurant_employee_id', 'email'], name='rest_employee__id_email_idx'),
        ),
    ]
