# Generated by Django 5.0.9 on 2024-11-08 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurantemployee_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='sessions',
        ),
    ]
