# Generated by Django 5.0.6 on 2024-06-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_restaurant_cep_remove_restaurant_city_and_more'),
        ('restaurant_client', '0004_restaurantclient_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='clients',
            field=models.ManyToManyField(related_name='restaurants', to='restaurant_client.restaurantclient'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
