# Generated by Django 5.0.9 on 2024-11-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_restaurant_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='role',
            field=models.CharField(choices=[('RESTAURANTCUSTOMER', 'RestaurantCustomer'), ('ADMIN', 'Admin'), ('RESTAURANT_ADMIN', 'Restaurant Admin'), ('RESTAURANT_STAFF', 'Restaurant Staff')], default='RESTAURANT_ADMIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurantemployee',
            name='role',
            field=models.CharField(choices=[('RESTAURANTCUSTOMER', 'RestaurantCustomer'), ('ADMIN', 'Admin'), ('RESTAURANT_ADMIN', 'Restaurant Admin'), ('RESTAURANT_STAFF', 'Restaurant Staff')], default='RESTAURANT_STAFF', max_length=20),
        ),
    ]
