# Generated by Django 5.0.9 on 2024-12-23 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_restaurant_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurantemployee',
            table='restaurant_employee',
        ),
    ]
