# Generated by Django 5.0.9 on 2024-12-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_restaurantemployee_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantemployee',
            name='name',
        ),
        migrations.AddField(
            model_name='restaurantemployee',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='restaurantemployee',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='restaurantemployee',
            index=models.Index(fields=['first_name', 'last_name', 'phone'], name='restaurant__employee_idx'),
        ),
    ]
