# Generated by Django 5.0.9 on 2024-12-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_restaurantemployee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantemployee',
            name='country_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
