# Generated by Django 5.0.9 on 2024-12-27 05:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_restaurantemployee_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedHours',
            fields=[
                ('blocked_hours_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blocked_hours',
            },
        ),
        migrations.CreateModel(
            name='CuisineType',
            fields=[
                ('cuisine_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cuisine_type',
            },
        ),
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Restaurant Categories',
                'db_table': 'restaurant_category',
            },
        ),
        migrations.CreateModel(
            name='RestaurantUnit',
            fields=[
                ('unit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_main_unit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'restaurant_unit',
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('working_hours_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'working_hours',
            },
        ),
        migrations.RemoveIndex(
            model_name='restaurantemployee',
            name='restaurant__employee_idx',
        ),
        migrations.RenameField(
            model_name='restaurantemployee',
            old_name='restaurant_employee_id',
            new_name='employee_id',
        ),
        migrations.RemoveField(
            model_name='restaurantemployee',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='restaurantemployee',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='restaurantemployee',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine_types',
            field=models.ManyToManyField(related_name='restaurants', to='restaurant.cuisinetype'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='restaurant.restaurantcategory'),
        ),
        migrations.AddField(
            model_name='restaurantunit',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='blockedhours',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_hours', to='restaurant.restaurantunit'),
        ),
        migrations.AddField(
            model_name='restaurantemployee',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='restaurant.restaurantunit'),
        ),
        migrations.AddIndex(
            model_name='restaurantemployee',
            index=models.Index(fields=['first_name', 'last_name', 'email'], name='restaurant_employee_idx'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='restaurant.restaurantunit'),
        ),
        migrations.AlterUniqueTogether(
            name='restaurantunit',
            unique_together={('restaurant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='workinghours',
            unique_together={('unit', 'day_of_week')},
        ),
    ]
