# Generated by Django 5.0.6 on 2024-07-19 02:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reserver', models.CharField(db_index=True, max_length=100)),
                ('amount_of_people', models.IntegerField()),
                ('amount_of_hours', models.IntegerField()),
                ('time', models.IntegerField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('reservation_hash', models.CharField(db_index=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
            options={
            },
        ),
        migrations.CreateModel(
            name='RestaurantVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
