# Generated by Django 5.0.9 on 2024-12-31 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation', '0001_initial'),
        ('restaurant', '0001_initial'),
        ('restaurant_customer', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_reservations', to='restaurant_customer.restaurantcustomer'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='unit.unit'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['reserver', 'start_time', 'end_time', 'reservation_date', 'reservation_hash'], name='reservation_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(check=models.Q(('amount_of_people__gt', 0)), name='positive_people_amount'),
        ),
    ]
