# Generated by Django 5.0.9 on 2024-11-02 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_initial'),
        ('restaurant', '0002_alter_restaurantemployee_restaurant'),
        ('restaurant_customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='restaurantvisit',
            name='restaurant_customer',
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_reservations', to='restaurant_customer.restaurantcustomer'),
        ),
        migrations.AddField(
            model_name='restaurantvisit',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='restaurant_customer.restaurantcustomer'),
        ),
        migrations.AlterField(
            model_name='restaurantvisit',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='restaurant.restaurant'),
        ),
    ]
