# Generated by Django 5.0.6 on 2024-06-26 03:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_rename_amountofhours_reservation_amount_of_hours_and_more'),
        ('restaurant', '0002_remove_restaurant_cep_remove_restaurant_city_and_more'),
        ('restaurant_client', '0003_restaurantclient_birthdate_restaurantclient_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='hash',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_hash',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='restaurant_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_reservations', to='restaurant_client.restaurantclient'),
        ),
    ]
