# Generated by Django 5.0.9 on 2024-11-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_reservation_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('finished', 'Finished')], default='confirmed', max_length=20),
        ),
    ]
