# Generated by Django 5.0.8 on 2024-11-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_reservation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
