# Generated by Django 5.0.8 on 2024-11-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservation_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='observation',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
