# Generated by Django 5.0.9 on 2024-12-04 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20241204_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservation.restaurantvisit'),
        ),
    ]
