# Generated by Django 5.0.9 on 2024-12-04 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_alter_reservation_visit'),
        ('restaurant', '0004_alter_restaurant_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='visit',
        ),
        migrations.AddField(
            model_name='reservation',
            name='country_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(max_length=70, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurant.restaurant'),
        ),
        migrations.DeleteModel(
            name='RestaurantVisit',
        ),
    ]
