# Generated by Django 5.0.9 on 2024-12-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_alter_reservation_restaurant'),
        ('restaurant', '0004_alter_restaurant_table'),
        ('restaurant_customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reservation',
            name='reservation_reserve_9df32c_idx',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['reserver', 'start_time', 'end_time', 'date', 'reservation_hash'], name='reservation_reserve_9df32c_idx'),
        ),
    ]
