# Generated by Django 5.0.9 on 2024-12-09 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_alter_reservation_end_time_and_more'),
        ('restaurant_customer', '0002_remove_restaurantcustomer_reservations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_reservations', to='restaurant_customer.restaurantcustomer'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(max_length=70),
        ),
    ]
