# Generated by Django 5.0.9 on 2024-12-23 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_alter_reservation_customer_alter_reservation_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservation',
            table='reservation',
        ),
    ]
