# Generated by Django 5.0.9 on 2024-12-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0018_fix_reservation_hash_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='amount_of_hours',
            field=models.PositiveIntegerField(),
        ),
    ]
